Multithread support for wolfMQTT-SN
wolfSSL/wolfMQTT pull request #176
Opened 2020-10-15 14:24 UTC by embhorn

Adding multithread support to the sensor network client library. Also adds a new SN multithread example that demonstrates the API. Configure with `--enable-sn --enable-mt`. Tested with QoS 0,1, and 2.

2020-10-15 22:14 UTC, dgarske requested changes
All code looks good and functionally tests out against SN-Gateway/Broker. Just a couple minor warnings I found (some old). Thanks!

2020-10-15 22:14 UTC, dgarske commented on src/mqtt_client.c
> +            SN_Packet_TypeDesc(wait_type), wait_type, wait_packet_id);
If building with `CC=g++` get a cast issue here. Should be `SN_Packet_TypeDesc((SN_MsgType)wait_type)`.

Same for line 736 case above. Needs to be `MqttPacket_TypeDesc((MqttPacketType)wait_type)`.

2020-10-15 22:14 UTC, dgarske commented on src/mqtt_client.c
> +    #ifdef WOLFMQTT_NONBLOCK
```
src/mqtt_client.c:3863:9: warning: Value stored to 'rc' is never read
        rc = SN_Client_WaitType(client, NULL,
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-10-15 22:14 UTC, dgarske commented on examples/sn-client/sn-client.c
> +        /* Short topic name subscribe */
Above subscribe warning:

```
examples/sn-client/sn-client.c:254:9: warning: Value stored to 'rc' is never read
        rc = SN_Client_Subscribe(&mqttCtx->client, &subscribe);
        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2020-10-16 15:54 UTC, embhorn commented on examples/sn-client/sn-client.c
> +        /* Short topic name subscribe */
Couldn't reproduce this one with `CC=g++`, but I fixed it anyway.

2020-10-16 16:05 UTC, dgarske approved these changes

2020-10-16 16:05 UTC, merged