Nonblock fixes
wolfSSL/wolfMQTT pull request #202
Opened 2021-02-12 03:16 UTC by embhorn

Fixes error handling in WIN32 with nonblock.
Fixes issue with large payload (> tx buffer size) in nonblock.

These issues were first reported in Zd10793.

2021-02-12 18:52 UTC, dgarske requested changes

2021-02-12 18:52 UTC, dgarske commented on examples/mqttnet.c
> +#ifdef _WIN32
This type logic should be handled at top with `SOERROR_T` macro. Odd because `_WIN32` should define `USE_WINDOWS_API`. So might need to make an adjustment there.

2021-02-12 18:52 UTC, dgarske commented on examples/mqttnet.c
> +            #ifdef _WIN32
Let's add a macro for getting the SO_ERROR and also macros for `EINPROGRESS` and `EINPROGRESS` vs `WSAEWOULDBLOCK` and `WSAEINPROGRESS`. This will simplify the repeated `#if` logic blocks below.

2021-02-12 18:52 UTC, dgarske commented on src/mqtt_client.c
> +            publish->buffer_pos += client->write.len;    //After sending the message new position is going to be current + client->write.len
Line length and `//` comment should be style `/* */` (recommend putting on line above).

2021-02-15 22:11 UTC, embhorn commented on examples/mqttnet.c
> +#ifdef _WIN32
Check

2021-02-15 22:13 UTC, embhorn commented on examples/mqttnet.c
> +            #ifdef _WIN32
All done except `NetConnect`, which also checks against errno (unlike the read / write)

```
                /* Check for error */
                GET_SOCK_ERROR(sock->fd, SOL_SOCKET, SO_ERROR, so_error);
                if (
            #ifndef _WIN32
                        (errno == EINPROGRESS) ||
            #endif
                        SOCK_EQ_ERROR(so_error))
                {
```

2021-02-15 22:16 UTC, dgarske requested changes

2021-02-15 22:16 UTC, dgarske commented on examples/mqttnet.c
> +                        SOCK_EQ_ERROR(so_error))
Instead of a macro for the error check, I was suggesting a macro for the error code and keeping the if logic here.

```
#ifdef _WIN32
    #define SOCKET_EWOULDBLOCK WSAEWOULDBLOCK
    #define SOCKET_EINPROGRESS WSAEINPROGRESS
#else
    #define SOCKET_EWOULDBLOCK EWOULDBLOCK
    #define SOCKET_EINPROGRESS EINPROGRESS
#endif
```

And keep the existing `if` logic...

2021-02-15 23:00 UTC, embhorn commented on examples/mqttnet.c
> +                        SOCK_EQ_ERROR(so_error))
Reason I went with a logic macro, is because WIN32 checks
`(((e) == WSAEWOULDBLOCK) || ((e) == WSAEINPROGRESS))`

...while others check 
`(((e) == EWOULDBLOCK) || ((e) == EAGAIN))`

So using your scheme I would still need the WIN32 conditional in every section.

2021-02-15 23:01 UTC, embhorn commented on examples/mqttnet.c
> +                        SOCK_EQ_ERROR(so_error))
I do have a couple other changes, though.

2021-02-15 23:12 UTC, dgarske approved these changes

2021-02-15 23:16 UTC, merged