fix memory leak in OSX wm_SemInit()/wm_SemFree() wrappers
wolfSSL/wolfMQTT pull request #218
Opened 2021-06-14 23:29 UTC by douzzer

also adds `MQTT_CODE_ERROR_SYSTEM`.

2021-06-14 23:36 UTC, dgarske requested changes

2021-06-14 23:36 UTC, dgarske commented on src/mqtt_client.c
> +        if (*s == NULL)
Also check s for NULL

2021-06-15 02:34 UTC, douzzer commented on src/mqtt_client.c
> +        if (*s == NULL)
:face_palm: right, thanks!

2021-06-15 15:23 UTC, dgarske approved these changes

2021-06-15 15:23 UTC, merged