Fix chunked publish with non-block
wolfSSL/wolfMQTT pull request #223
Opened 2021-07-12 20:23 UTC by embhorn

Created `MQTT_CODE_PUB_CONTINUE` to be used when publishing a payload larger than the MQTT buffer size (publish in chunks). 

```
do {
    rc = MqttClient_Publish(client, publish);
}while ((rc != MQTT_CODE_PUB_CONTINUE) && (rc != MQTT_CODE_CONTINUE));
```

This fixes an issue from ZD12608

This fixes #192

2021-07-12 23:38 UTC, dgarske approved these changes

2021-07-13 21:56 UTC, dgarske requested changes
This is a great test addition. Just a few minor feedback items.

2021-07-13 21:56 UTC, dgarske commented on examples/mqttexample.c
> +    *fileLen = (int) ftell(file);
Please check this. Could return negative?

2021-07-13 21:56 UTC, dgarske commented on examples/mqttexample.c
> +    //PRINTF("File %s is %d bytes", filePath, *fileLen);
Feel free to put this back with `DEBUG_WOLFMQTT`.

2021-07-13 21:56 UTC, dgarske commented on examples/mqttexample.c
> +        rc = EXIT_FAILURE;
Can we use a better return code?

2021-07-15 17:26 UTC, dgarske requested changes

2021-07-15 17:26 UTC, dgarske commented on examples/mqttexample.h
> +#define DEFAULT_MAX_PKT_SZ      1024*1024 /* The max MQTT control packet size
Can we also allow a user to override this?

2021-07-15 17:26 UTC, dgarske commented on examples/mqttexample.c
> +        rc = EXIT_FAILURE;
Can we improve the error codes returned in this function?

2021-07-15 17:38 UTC, embhorn commented on examples/mqttexample.h
> +#define DEFAULT_MAX_PKT_SZ      1024*1024 /* The max MQTT control packet size
From the example CLI:
`-P <num>    Max packet size the client will accept, default: 1048576`

2021-07-15 17:42 UTC, embhorn commented
Weird... I must have undone that return code fix when I changed something else in there.

2021-07-15 18:58 UTC, dgarske requested changes

2021-07-15 18:58 UTC, dgarske commented on examples/mqttexample.c
> +    #warning No filesystem, so need way to load example firmware file to publish
The `#warning` isn't valid for Windows VS needs `#pragma message("")`. Note I would prefer not to throw a build warning here. Consider returning an error code instead and let it be a run-time failure.

```
./configure --enable-mqtt5 --enable-nonblock CFLAGS="-DNO_FILESYSTEM" && make

examples/mqttexample.c:701:6: error: No filesystem, so need way to load example firmware file to publish [-Werror,-W#warnings]
    #warning No filesystem, so need way to load example firmware file to publish
     ^
examples/mqttexample.c:701:6: error: No filesystem, so need way to load example firmware file to publish [-Werror,-W#warnings]
    #warning No filesystem, so need way to load example firmware file to publish
     ^
1 error generated.
examples/firmware/fwpush.c:81:41: error: unused parameter 'publish' [-Werror,-Wunused-parameter]
static int mqtt_publish_cb(MqttPublish *publish) {
                                        ^
1 error generated.
examples/mqttexample.c:701:6: error: No filesystem, so need way to load example firmware file to publish [-Werror,-W#warnings]
    #warning No filesystem, so need way to load example firmware file to publish
     ^
examples/mqttexample.c:701:6: error: No filesystem, so need way to load example firmware file to publish [-Werror,-W#warnings]
    #warning No filesystem, so need way to load example firmware file to publish
     ^
```

2021-07-15 18:58 UTC, dgarske commented on examples/firmware/fwpush.c
> -static int fwfile_load(const char* filePath, byte** fileBuf, int *fileLen)
Above build error with NO_FILESYSTEM.

```
examples/firmware/fwpush.c:81:41: error: unused parameter 'publish' [-Werror,-Wunused-parameter]
static int mqtt_publish_cb(MqttPublish *publish) {
                                        ^
```

2021-07-15 18:58 UTC, dgarske commented on examples/mqttclient/mqttclient.c
> +    if (rc == MQTT_CODE_SUCCESS) {
Else case is not handled here... no error reported for failure like file doesn't exist or feature not compiled in...

2021-07-15 19:42 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +    if (rc == MQTT_CODE_SUCCESS) {
That was by design, but I can change it. The failure to open is displayed, but the example continues:

```
./examples/mqttclient/mqttclient -f test
MQTT Client: QoS 0, Use TLS 0
MQTT Net Init: Success (0)
MQTT Init: Success (0)
NetConnect: Host test.mosquitto.org, Port 1883, Timeout 5000 ms, Use TLS 0
MQTT Socket Connect: Success (0)
MQTT Connect: Proto (v5), Success (0)
MQTT Connect Ack: Return Code 0, Session Present 0
MQTT Subscribe: Success (0)
  Topic wolfMQTT/example/testTopic, Qos 0, Return Code 0
File test does not exist!
MQTT Waiting for message...
```

2021-07-15 19:54 UTC, dgarske commented on examples/mqttclient/mqttclient.c
> +    if (rc == MQTT_CODE_SUCCESS) {
If NO_FILESYSTEM is defined then nothing is printed. Maybe replace the `#warning` with a PRINTF? I still think the return code should be printed on error.

2021-07-15 21:09 UTC, dgarske approved these changes
Excellent work. Thanks!

2021-07-15 21:09 UTC, merged