Add ability to parse pub props in msg CB
wolfSSL/wolfMQTT pull request #245
Opened 2021-11-05 20:04 UTC by embhorn

This is a feature request from ZD13146

2021-11-05 21:00 UTC, dgarske requested changes
Seems like a reasonable way to solve this. We do have a property callback, but I can understand wanting to access the properties in the publish callback as well.

2021-11-05 21:00 UTC, dgarske commented on src/mqtt_client.c
> +                        byte free)
`free` might be a reserved keyword. Consider different variable name.

2021-11-05 21:04 UTC, embhorn commented on src/mqtt_client.c
> +                        byte free)
Check

2021-11-05 21:05 UTC, embhorn commented
Let me try to get feedback from the customer before merging

2022-01-05 19:12 UTC, dgarske approved these changes

2022-02-01 20:21 UTC, embhorn commented on src/mqtt_client.c
> +                XMEMSET(use_packet_obj, 0, sizeof(MqttObject));
@dgarske   This fixes several fuzzer issues. There was stale data left from processing other incoming messages.

2022-02-01 20:33 UTC, dgarske requested changes

2022-02-01 20:33 UTC, dgarske commented on src/mqtt_client.c
> +                XMEMSET(use_packet_obj, 0, sizeof(MqttObject));
Would prefer `sizeof(client->msg)`. Also the read lock is held here, which is good, but consider also wrapping in `rc = wm_SemLock(&client->lockClient);` and `wm_SemUnlock(&client->lockClient);`.

2022-02-01 23:04 UTC, dgarske approved these changes

2022-02-10 22:03 UTC, dgarske approved these changes

2022-02-10 22:12 UTC, embhorn reviewed
Excellent. Fix for property handling checks out.

2022-02-11 17:00 UTC, dgarske commented
Customer confirmed fix. Eric also approved my changes and I approved him. Merging for both of us.

2022-02-11 17:00 UTC, merged