Fixes for multithreading with non-blocking
wolfSSL/wolfMQTT pull request #252
Opened 2021-12-01 21:59 UTC by dgarske

* Add non-blocking support to multi-threaded example.
* Fix for read lock issue in non-blocking mode with multiple threads.
ZD 12793

2021-12-01 22:57 UTC, embhorn requested changes
With `--enable-all` I am seeing a hang with 
`./scripts/nbclient.test`

Can also reproduce hang with 
`./examples/nbclient/nbclient -h localhost -q 2`
Have to actually terminate nbclient process to complete.

Also `./scripts/multithread.test` is failing.

```
MQTT Client: QoS 0, Use TLS 1
Use "Ctrl+c" to exit.
MQTT Net Init: Success (0)
MQTT Init: Success (0)
NetConnect: Host localhost, Port 8883, Timeout 5000 ms, Use TLS 1
MQTT TLS Setup (1)
1638399261: New connection from 127.0.0.1:37348 on port 8883.
MQTT Socket Connect: Continue (-101)


Multithread Client failed! TLS=On, QoS=0
```

2021-12-01 22:57 UTC, embhorn commented on src/mqtt_client.c
> +            client->read.isLocked = 1;
This was the primary issue? So the state was not being preserved between subsequent calls if non-blocking was returned.

2021-12-02 12:13 UTC, lygstate commented
This is also be fixed by https://github.com/wolfSSL/wolfMQTT/pull/213

2021-12-10 15:33 UTC, embhorn requested changes

2021-12-16 14:14 UTC, lygstate commented on src/mqtt_client.c
> +        case MQTT_MSG_ACK:
When acking, we can still doing receiving, I am not sureif the  MQTT_MSG_ACK state for read is proper, in fact, the intension of MQTT_MSG_ACK is doing `write`, not doing `read`

2021-12-16 15:35 UTC, lygstate commented on src/mqtt_client.c
>          /* reset state */
When in MQTT_MSG_WAIT state,
* None data are `read`, we can switch to MQTT_MSG_BEGIN and release the lock
* All data are `read`, we can switch to MQTT_MSG_BEGIN and release the lock
* If partial data are read, we should continue reading and do not release the lockRecv
In other words, 

```
#ifdef WOLFMQTT_NONBLOCK
    if (rc == MQTT_CODE_CONTINUE) {
        return rc;
    }
#endif
```
Should handled before wm_SemUnlock(&client->lockRecv);

2021-12-16 15:46 UTC, dgarske commented on src/mqtt_client.c
>          /* reset state */
Thank you @lygstate ! This is great feedback!! Let me know if you see anything else. I will push some more fixes today.

2021-12-16 17:04 UTC, lygstate commented
I suggest getting MqttPendResp not limited to WOLFMQTT_MULTITHREAD.
Making the code clearer.

```
 src/mqtt_client.c      | 32 ++++++++++++++++++++------------
 wolfmqtt/mqtt_client.h |  4 ++--
 wolfmqtt/mqtt_packet.h |  2 --
 3 files changed, 22 insertions(+), 16 deletions(-)

diff --git a/src/mqtt_client.c b/src/mqtt_client.c
index e5df382..982a10c 100644
--- a/src/mqtt_client.c
+++ b/src/mqtt_client.c
@@ -152,7 +152,9 @@ static int MqttClient_Publish_ReadPayload(MqttClient* client,
     }
 
 #endif
+#endif /* WOLFMQTT_MULTITHREAD */
 
+/* inform this and other threads of expected response */
 /* These RespList functions assume caller has locked client->lockClient mutex */
 static int MqttClient_RespList_Add(MqttClient *client,
     MqttPacketType packet_type, word16 packet_id, MqttPendResp *newResp,
@@ -160,10 +162,16 @@ static int MqttClient_RespList_Add(MqttClient *client,
 {
     MqttPendResp *tmpResp;
     MqttMsgStat *pend_stat;
+    int rc = MQTT_CODE_ERROR_BAD_ARG;
 
     if (client == NULL || packet_obj == NULL)
-        return MQTT_CODE_ERROR_BAD_ARG;
-
+        return rc;
+#ifdef WOLFMQTT_MULTITHREAD
+    rc = wm_SemLock(&client->lockClient);
+    if (rc != 0) {
+        return rc;
+    }
+#endif
 #ifdef WOLFMQTT_DEBUG_CLIENT
     PRINTF("PendResp Add: %p packet_obj:%p, Type %s (%d), ID %d",
         newResp, packet_obj, MqttPacket_TypeDesc(packet_type), packet_type, packet_id);
@@ -178,6 +186,9 @@ static int MqttClient_RespList_Add(MqttClient *client,
         #ifdef WOLFMQTT_DEBUG_CLIENT
             PRINTF("Pending Response already in list!");
         #endif
+#ifdef WOLFMQTT_MULTITHREAD
+            wm_SemUnlock(&client->lockClient);
+#endif
             return MQTT_CODE_ERROR_BAD_ARG;
         }
     }
@@ -202,6 +213,9 @@ static int MqttClient_RespList_Add(MqttClient *client,
         client->lastPendResp->next = newResp;
         client->lastPendResp = newResp;
     }
+#ifdef WOLFMQTT_MULTITHREAD
+            wm_SemUnlock(&client->lockClient);
+#endif
     return 0;
 }
 
@@ -291,7 +305,6 @@ static int MqttClient_RespList_Find(MqttClient *client,
     }
     return rc;
 }
-#endif /* WOLFMQTT_MULTITHREAD */
 
 #ifdef WOLFMQTT_V5
 static int Handle_Props(MqttClient* client, MqttProp* props, byte use_cb)
@@ -1222,19 +1235,14 @@ int MqttClient_Connect(MqttClient *client, MqttConnect *mc_connect)
         }
         client->write.len = rc;
 
-    #ifdef WOLFMQTT_MULTITHREAD
-        rc = wm_SemLock(&client->lockClient);
-        if (rc == 0) {
-            /* inform other threads of expected response */
-            rc = MqttClient_RespList_Add(client, MQTT_PACKET_TYPE_CONNECT_ACK,
-                    0, &mc_connect->pendResp, &mc_connect->ack);
-            wm_SemUnlock(&client->lockClient);
-        }
+        rc = MqttClient_RespList_Add(client, MQTT_PACKET_TYPE_CONNECT_ACK,
+                0, &mc_connect->pendResp, &mc_connect->ack);
         if (rc != 0) {
+        #ifdef WOLFMQTT_MULTITHREAD
             wm_SemUnlock(&client->lockSend);
+        #endif
             return rc; /* Error locking client */
         }
-    #endif
 
         /* Send connect packet */
         rc = MqttPacket_Write(client, client->tx_buf, client->write.len);
diff --git a/wolfmqtt/mqtt_client.h b/wolfmqtt/mqtt_client.h
index ef297d3..eedcf35 100644
--- a/wolfmqtt/mqtt_client.h
+++ b/wolfmqtt/mqtt_client.h
@@ -177,9 +177,9 @@ typedef struct _MqttClient {
     wm_Sem lockSend;
     wm_Sem lockRecv;
     wm_Sem lockClient;
-    struct _MqttPendResp* firstPendResp; /* protected with client lock */
-    struct _MqttPendResp* lastPendResp;  /* protected with client lock */
 #endif
+    MqttPendResp* firstPendResp; /* protected with client lock for WOLFMQTT_MULTITHREAD */
+    MqttPendResp* lastPendResp;  /* protected with client lock for WOLFMQTT_MULTITHREAD */
 } MqttClient;
 
 
diff --git a/wolfmqtt/mqtt_packet.h b/wolfmqtt/mqtt_packet.h
index d87f0db..3d6d231 100644
--- a/wolfmqtt/mqtt_packet.h
+++ b/wolfmqtt/mqtt_packet.h
@@ -305,7 +305,6 @@ typedef struct _MqttMsgStat {
 #endif
 } MqttMsgStat;
 
-#ifdef WOLFMQTT_MULTITHREAD
 /* Pending Response Structure */
 typedef struct _MqttPendResp {
     word16          packet_id;
@@ -321,7 +320,6 @@ typedef struct _MqttPendResp {
     struct _MqttPendResp* next;
     struct _MqttPendResp* prev;
 } MqttPendResp;
-#endif /* WOLFMQTT_MULTITHREAD */
 
 
 /* CONNECT PACKET */

```

2021-12-17 02:47 UTC, lygstate commented
Get the state-machine working is hard,
before this patch, in WOLFMQTT_MULTITHREAD mode, the following function
```
 rc = MqttPacket_Write(client, client->tx_buf, client->write.len);
```
will not exit before all data are sent, but now
It's may only sent partial data and return MQTT_CODE_CONTINUE, so we
have no reason to release lockSend, only when all data are sent, we can release the lockSend.

2021-12-17 02:48 UTC, lygstate commented on wolfmqtt/mqtt_packet.h
> +    byte isReadLocked:1;
These two lock can also be available on non-blocking mode to tracing the read/write state.

2021-12-17 03:37 UTC, lygstate commented
MQTT_CODE_CONTINUE should disabled when WOLFMQTT_NONBLOCK is not defined

2021-12-17 11:28 UTC, lygstate commented on src/mqtt_client.c
> +    MqttPublishResp resp; /* for any ACK required */
Stroage resp on stack is not proper, as MqttPacket_Write may return MQTT_CODE_CONTINUE in non-blocking mode.
And then we will use zeroed resp for publish.

2021-12-17 17:39 UTC, dgarske commented on src/mqtt_client.c
> +    MqttPublishResp resp; /* for any ACK required */
Good eye @lygstate. I am aware of this issue still working on how to solve it. Your feedback on this PR is very helpful, thank you.

2021-12-23 04:28 UTC, lygstate commented on examples/multithread/multithread.c
> +    mqttCtx->useNonBlockMode = 1;
Maybe a better way is to remove WOLFMQTT_NONBLOCK macro and always using useNonBlockMode option?
Without WOLFMQTT_NONBLOCK  macro, the code is complicated.

2022-01-05 01:03 UTC, dgarske commented
Note: @embhorn there is a bug with multithread with the `-T` flag when not using non-blocking. I will push a fix for in the morning. Then we should finalize and merge this before the release.

2022-01-05 17:04 UTC, embhorn reviewed
Testing `--enable-mt --enable-nonblock`, the multithread test stops responding to pings after two:

client
```
MQTT Message: Topic wolfMQTT/example/testTopic, Qos 0, Id 0, Len 6, 6, 0
Payload (0 - 6): test11
MQTT Message: Done
Timeout timer 30 seconds
Sending ping keep-alive
Timeout timer 30 seconds
Sending ping keep-alive
Timeout timer 30 seconds
MQTT Ping Keep Alive Error: Error (Timeout) (-7)
Timeout timer 30 seconds
Timeout timer 30 seconds
Timeout timer 30 seconds
Timeout timer 30 seconds
Timeout timer 30 seconds
Timeout timer 30 seconds
Timeout timer 30 seconds
```
broker
```
1641401515: Sending PUBLISH to WolfMQTTClient (d0, q0, r0, m0, 'wolfMQTT/example/testTopic', ... (6 bytes))
1641401545: Received PINGREQ from WolfMQTTClient
1641401545: Sending PINGRESP to WolfMQTTClient
1641401575: Received PINGREQ from WolfMQTTClient
1641401575: Sending PINGRESP to WolfMQTTClient
1641401668: Client WolfMQTTClient has exceeded timeout, disconnecting.
```

2022-01-05 19:55 UTC, embhorn approved these changes
Ready to go!

2022-01-05 19:56 UTC, merged