Porting WolfMQTT to NUCLEO F767ZI  with TOPPERS OS
wolfSSL/wolfMQTT pull request #254
Opened 2021-12-15 15:27 UTC by nekoman2187

Porting WolfMQTT to STM's NUCLEO F767ZI board with TOPPERS OS
Please review!
kojo-san's request to embed and test Wolfssl5.0 was not possible!
Sorry about that.

2021-12-16 17:35 UTC, dgarske requested changes
Please reference the existing wolfMQTT files in the repo, not add new ones. If you need changes specific to TOPPERS OS then use a macro in the existing code.

2021-12-16 17:35 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/.vscode/settings.json
> +// Place your settings in this file to overwrite default and user settings.
I am not sure `//` comments in JSON are technically allowed. Would it be possible to add a `"comment": "Place your settings in this file to overwrite default and user settings."` field instead?

2021-12-16 17:35 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/examples/azure/azureiothub.h
> +/* azureiothub.h
We cannot have another copy of the wolfMQTT code in `IDE/TOPPERS/wolfmqtt`. It should reference the files in the wolfMQTT root.

2021-12-22 12:49 UTC, nekoman2187 commented on IDE/TOPPERS/wolfmqtt/.vscode/settings.json
> +// Place your settings in this file to overwrite default and user settings.
No need for options in settings.json

2021-12-22 12:49 UTC, nekoman2187 commented on IDE/TOPPERS/wolfmqtt/examples/azure/azureiothub.h
> +/* azureiothub.h
Fixed the configuration

2021-12-22 16:57 UTC, dgarske requested changes

2021-12-22 16:57 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/README.md
> +1. copy IDE/TOPPERS/wolfmqtt to trunk-473/trunk
Can we implement a way that does not require coping files? I would prefer reference `../..`. Also please move README.md and Makefile into `IDE/TOPPERS` eliminating the `wolfmqtt` dir. Also you will need to add an include.am so these files are included with `make dist`.


`IDE/TOPPERS/include.am`
```
# vim:ft=automake
# included from Top Level Makefile.am
# All paths should be given relative to the root

EXTRA_DIST+= IDE/TOPPERS/README.md
EXTRA_DIST+= IDE/TOPPERS/Makefile
```

2021-12-22 16:57 UTC, dgarske commented on examples/azure/azureiothub.c
> +     lTime = XTIME(0);
Is `wc_GetTime` missing for you? The "wc_GetTime" API was added in wolfSSL 3.9.1.

2021-12-22 16:57 UTC, dgarske commented on wolfmqtt/user_settings.h
> +/* used by TOPPERS OS */
This file must reside in `IDE/TOPPERS`. It cannot be in a shared location.

2021-12-22 16:57 UTC, dgarske commented on wolfmqtt/user_settings.h
> +/* used by TOPPERS OS */
It needs the standard wolfMQTT file header and should have normal `#ifndef _TOPPERS_USER_SETTINGS_H` macro guards for recursive include protection... like `#pragma once` does.

2021-12-22 16:57 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/Makefile
> +C_FLAGS += -DHAVE_CONFIG_H
Please consolidate these:

```
# wolfSSL flags
WOLF_FLAGS  = -DHAVE_CONFIG_H
WOLF_FLAGS += -DWOLFSSL_USER_SETTINGS
WOLF_FLAGS += -DWOLFMQTT_USER_SETTINGS
WOLF_FLAGS += -DTOPPERS

C_FLAGS += $(WOLF_FLAGS)
CXX_FLAGS += $(WOLF_FLAGS)
```

Also would prefer to not have all these duplicated for C and CXX. Please setup a single build variable for each group.

2021-12-22 16:57 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/Makefile
> +INCLUDE_PATHS += -I../../zlib-1.2.11/src
Do we need the zlib and wolfssl versions fixed? Can't we require the names `zlib` and `wolfssl`? This is more common.

2021-12-22 16:57 UTC, dgarske commented on IDE/TOPPERS/wolfmqtt/README.md
> +1. copy IDE/TOPPERS/wolfmqtt to trunk-473/trunk
If files still need adjusted please inside a .sh script in IDE/TOPPERS.

2021-12-24 02:35 UTC, watanabeakinori commented on examples/azure/azureiothub.c
> +     lTime = XTIME(0);
Calling wc_GetTime will return the error BUFFER_E
time_t is 64bit and timeSize is 32bit.
So I'm calling XTIME directly.
What is the purpose of this error checking?
Also, is there a way to work around this?
(Does the long type have to be 64bit?).

2021-12-24 02:40 UTC, nekoman2187 commented on examples/azure/azureiothub.c
> +     lTime = XTIME(0);
Calling wc_GetTime will return the error BUFFER_E
time_t is 64bit and timeSize is 32bit.
So I'm calling XTIME directly.
What is the purpose of this error checking?
Also, is there a way to work around this?
(Does the long type have to be 64bit?).

2021-12-24 05:03 UTC, nekoman2187 commented on IDE/TOPPERS/wolfmqtt/Makefile
> +INCLUDE_PATHS += -I../../zlib-1.2.11/src
The base project specifies the version
The base project has specified a version, and the specified version has already been imported.
Another specified makefile contains the following
INCLUDES += -I$(SRCDIR)/... /wolfssl-4.7.0 
INCLUDES += -I$(SRCDIR)/... /zlib-1.2.11/src
To remove the above
You will need to put a fix for the makefile in the readme
You also need to change the directory name and
in c_cpp_properties.json
 "${workspaceFolder}/... /zlib-1.2.11/src",
 "${workspaceFolder}/... /wolfssl-4.7.0"
must be changed.
Do you want to do that?
I'm not sure.

2022-02-25 19:47 UTC, dgarske requested changes

2022-02-25 19:47 UTC, dgarske commented on examples/azure/azureiothub.c
> +     lTime = XTIME(0);
Build wolfCrypt using `TIME_T_NOT_64BIT`. This will make time_t 32-bits.

2022-02-25 19:47 UTC, dgarske commented on wolfmqtt/user_settings.h
> +/* used by TOPPERS OS */
Please move user_settings.h into IDE/TOPPERS.

2022-02-25 19:47 UTC, dgarske commented on wolfmqtt/user_settings.h
> +/* used by TOPPERS OS */
Please add recursive include protections.

2022-03-06 13:06 UTC, nekoman2187 commented on examples/azure/azureiothub.c
> +     lTime = XTIME(0);
TIME_T_NOT_64BIT could not be used because configure is not used.
I gave _USE_LONG_TIME_T in the makefile to arm-none-eabi-gcc

2022-03-08 18:55 UTC, dgarske approved these changes
@nekoman2187 , I resolved the merge conflict and did a squash merge. Changes look good. Marking approved.

2022-03-11 16:52 UTC, embhorn commented on IDE/F767ZI-TOPPERS/wolfmqtt-F767ZI-TOPPERS.sh
> +# tThis script is used in the F767ZI-TOPPERS project
"tThis" -> "This"

2022-03-11 21:23 UTC, embhorn requested changes
Looking great, a couple suggestions and things that need clarification.
I am not sure why `options.h` needs a new version. The script is already copying files from the base wolfMQTT folder, so just also `cp wolfmqtt/options.h.in options.h`

2022-03-11 21:23 UTC, embhorn commented on IDE/F767ZI-TOPPERS/Makefile
> +# trick rules into thinking we are in the root, when we are in the bulid dir
"bulid" -> "build"

2022-03-11 21:23 UTC, embhorn commented on IDE/F767ZI-TOPPERS/Makefile
> +INCLUDE_PATHS += -I../wolfssl/src
This assumes wolfssl is installed here, but I did not see anywhere in the README.md to install wolfSSL

2022-03-11 21:23 UTC, embhorn commented on IDE/F767ZI-TOPPERS/wolfmqtt-F767ZI-TOPPERS.sh
> +     cp ./options.h  ./wolfmq
What is this doing?

2022-03-16 12:13 UTC, nekoman2187 commented on IDE/F767ZI-TOPPERS/Makefile
> +# trick rules into thinking we are in the root, when we are in the bulid dir
Correction

2022-03-16 12:14 UTC, nekoman2187 commented on IDE/F767ZI-TOPPERS/Makefile
> +INCLUDE_PATHS += -I../wolfssl/src
Readme has been modified.

2022-03-18 12:51 UTC, embhorn approved these changes
Excellent, thanks for addressing those issues. Approved!

2022-03-29 19:53 UTC, merged