Fix for read state not getting reset if processing a QOS >= 1
wolfSSL/wolfMQTT pull request #288
Opened 2022-03-17 23:35 UTC by dgarske

ZD13880

2022-03-18 12:48 UTC, embhorn approved these changes
Successfully tested with customer's use case

2022-04-01 03:31 UTC, dgarske commented
Note: Had to cancel the CI jobs. Looks like last commit is causing an issue with multi-threaded with non-blocking tests. Also I plan to add additional tests for the WANT_WRITE -> MQTT_CODE_CONTINUE, since I believe there are places it is not properly handled correctly.

2022-04-04 20:02 UTC, embhorn requested changes
Excellent changes. `make check` succeeds with `--enable-all`

I am seeing a seg-fault with SN client 
```
./configure --enable-sn && make
./examples/sn-client/sn-client
```

```
MQTT-SN Client: QoS 0
MQTT-SN Net Init: Success (0)
MQTT-SN Init: Success (0)
NetConnect: Host localhost, Port 10000, Timeout 5000 ms, Use TLS 0
MQTT-SN Socket Connect: Success (0)
MQTT-SN Connect: gateway = localhost : 10000
....MQTT-SN Connect Ack: Return Code 0
MQTT-SN Register: topic = wolfMQTT/example/testTopic
....MQTT-SN Register Ack: rc = 0, topic id = 1
MQTT-SN Subscribe: topic name = wolfMQTT/example/testTopic
....MQTT-SN Subscribe Ack: topic id = 1, rc = 0
MQTT-SN Subscribe: topic name = wolfMQTT/example/#
....MQTT-SN Subscribe Ack: topic id = 2, rc = 0
MQTT-SN Publish: topic id = 1, rc = 0
Payload = test
MQTT-SN Subscribe Short Topic: topic ID = s1
MQTT-SN Message: Topic ID 1, Qos 0, Id 0, Len 4
Segmentation fault (core dumped)
```

2022-04-04 20:47 UTC, embhorn approved these changes

2022-04-04 21:45 UTC, merged