Add CMake support build
wolfSSL/wolfMQTT pull request #292
Opened 2022-04-07 00:20 UTC by elms

* use external wolfSSL tree or install location

2022-04-07 22:07 UTC, haydenroche5 requested changes

2022-04-07 22:07 UTC, haydenroche5 commented on CMakeLists.txt
> +# See "Building with CMake" in INSTALL for more.
Looks like this is leftover from the wolfSSL CMake. No INSTALL file in wolfMQTT repo that I can see.

2022-04-08 00:19 UTC, elms commented on CMakeLists.txt
> +# See "Building with CMake" in INSTALL for more.
@haydenroche5 Good prompt to add a section to `README.md` and fix that. Also matched an option I used for wolfTPM.

2022-04-08 19:57 UTC, haydenroche5 approved these changes

2022-04-08 20:30 UTC, dgarske approved these changes
Works as describe! Thanks

2022-04-08 20:30 UTC, merged