Support post-quantum KYBER_LEVEL1 and P256_KYBER_LEVEL1 with FALCON_LEVEL1 in wolfMQTT.
wolfSSL/wolfMQTT pull request #300
Opened 2022-06-02 21:40 UTC by anhu

2022-06-02 21:49 UTC, dgarske requested changes

2022-06-02 21:49 UTC, dgarske commented on examples/mqttexample.c
> +         */
Looks good. Remove your comment. You should put comments in the PR not in the code.

2022-06-02 21:49 UTC, dgarske commented on examples/mqttexample.c
> +                PRINTF("invalid post-quantum KEM specified");
"Invalid" case.

2022-06-02 22:00 UTC, anhu commented on wolfmqtt/mqtt_client.h
> + *  \note The callback function that cb points to does not have to initialize
hmmm....I don't know what the difference is and I don't know why mqtt has its own custom ones in the first place.  I'll look into it tomorrow.

2022-06-02 22:04 UTC, anhu commented on wolfmqtt/mqtt_client.h
> + *  \note The callback function that cb points to does not have to initialize
OH !!!   You mean call those functions after the callback returns!!  I get it now. Will do tomorrow.

2022-06-02 22:05 UTC, anhu commented
> Add a section in the README.md please showing steps to use PQ with MQTT. This would require the server to have PQ enabled to, so guessing there are many tips you can add.

Sure, will get to it tomorrow.

2022-06-03 16:51 UTC, dgarske approved these changes

2022-06-03 17:02 UTC, anhu commented
Not ready for merge yet. Still need to do README.md additions.

2022-06-03 19:57 UTC, dgarske approved these changes

2022-06-03 19:57 UTC, anhu commented
Firmware test is failing...repro'd on my local system. I still need to investigate.

2022-06-03 20:07 UTC, dgarske commented
> 

Don't investigate, just retry the test. It isn't you... it is because our tests use a public server and the tests sometimes collide. We don't have our own MQTT broker for testing....

2022-06-03 23:16 UTC, anhu commented
Already retried.  Repro'd locally, consistently and got seg fault.  Can't be result of collision .

2022-06-03 23:37 UTC, dgarske commented
> Already retried. Repro'd locally, consistently and got seg fault. Can't be result of collision .

That's great. Should be easy then. I won't merge yet.

2022-06-03 23:59 UTC, anhu commented
Yup.  Will investigate on Monday morning.

2022-06-06 19:28 UTC, dgarske approved these changes

2022-06-06 22:27 UTC, merged