wolfMQTT Release v1.14.1 preparation
wolfSSL/wolfMQTT pull request #308
Opened 2022-08-31 20:14 UTC by embhorn

Also revert #305

2022-08-31 20:18 UTC, dgarske requested changes

2022-08-31 20:18 UTC, dgarske commented on wolfmqtt/vs_settings.h
> +#if !defined(HAVE_CONFIG_H)
This `BUILDING_CMAKE` fixed a vcpkg issue. Do you have a plan for how to fix this in vcpkg with Windows Cmake?  I was not able to get the vcpkg update through without it. See https://github.com/microsoft/vcpkg/pull/25936

2022-08-31 20:24 UTC, embhorn commented on wolfmqtt/vs_settings.h
> +#if !defined(HAVE_CONFIG_H)
Yeah, I'll have to figure something else out. That change definitely breaks vcpkg / VS builds.

2022-08-31 20:26 UTC, embhorn commented on wolfmqtt/vs_settings.h
> +#if !defined(HAVE_CONFIG_H)
From zd14640
>The problem was as I explained earlier; the config used to build the wolfMQTT library in vcpkg was different from the config the application was using. I was able to resolve the issue by removing the section of the diff patch that changes wolfmqtt/vs_settings.h

2022-08-31 20:31 UTC, dgarske commented on wolfmqtt/vs_settings.h
> +#if !defined(HAVE_CONFIG_H)
That's fine, but you will likely need to find another solution for the vcpkg CI tests with wolfMQTT and Windows.

2022-08-31 20:35 UTC, dgarske approved these changes

2022-08-31 21:43 UTC, merged

2022-09-04 21:41 UTC, chenrui333 commented
Just heads up, [this merge build](https://github.com/wolfSSL/wolfMQTT/runs/8123500764) needs a rerun.