Add QNX IDE, Makefile, and remove source code exec bit
wolfSSL/wolfMQTT pull request #317
Opened 2023-02-23 18:04 UTC by JacobBarthelmeh

2023-02-23 22:06 UTC, JacobBarthelmeh commented
Builds off of https://github.com/wolfSSL/wolfssl/pull/6127

2023-07-17 14:19 UTC, embhorn commented
Hi @JacobBarthelmeh 

Could you please rebase this and re-request a review?

2023-07-17 15:31 UTC, embhorn requested changes
I did not build test. Do we have an automated build test for QNX / wolfSSL?

2023-07-17 15:31 UTC, embhorn commented on IDE/QNX/README.md
> +Then both projects can be imported as an momentics IDE project. To first build wolfSSL view the README located at wolfssl/IDE/QNX/README.md. Then to build wolfMQTT start momentics with the workspace
"an momentics" -> "a Momentics"

2023-07-17 15:31 UTC, embhorn commented on src/mqtt_packet.c
Should this be removed from the review?

2023-07-18 19:49 UTC, JacobBarthelmeh commented on src/mqtt_packet.c
it's a change for the execute bit on the file I noticed, it is outside of QNX use but just doing chmod 644 on the source file

2023-07-18 20:04 UTC, embhorn approved these changes

2023-07-18 20:04 UTC, merged