Zephyr port
wolfSSL/wolfMQTT pull request #333
Opened 2023-04-28 14:03 UTC by julek-wolfssl

2023-04-28 16:33 UTC, embhorn requested changes
Awesome! I have not tested yet, but please check out comments / questions.

2023-04-28 16:33 UTC, embhorn commented on zephyr/wolfMQTT_user_settings.h
Any particular reason for overriding the normal "user_settings.h"?

2023-04-28 16:33 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +
This should be irrelevant now:
https://github.com/zephyrproject-rtos/zephyr/pull/54628

2023-04-28 16:33 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +#endif
Can specify TLS with `-t` option
`mqttclient -t`

2023-04-28 16:33 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +#endif
Can specify host with `-h` option
`mqttclient -h <host_name>`

2023-04-28 16:33 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +#endif
Can specify port with `-p` option
`mqttclient -p <port_number>`

2023-04-28 18:37 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +
I tested on the latest release. I'll check with master when I get back.

2023-04-28 18:39 UTC, julek-wolfssl commented on zephyr/wolfMQTT_user_settings.h
I was following the same approach as in the wolfSSL Zephyr support. We usually have dedicated user settings for each use case. Is there anything missing that you think should go in here too?

2023-04-28 18:40 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +#endif
This example is for the Zephyr RTOS. I don't know how to pass in command line parameters there. I was also following the way that the Zephyr MQTT example defines the host, port, and topic.

2023-04-28 18:50 UTC, julek-wolfssl commented
Forgot to add new files to `include.am`

2023-05-01 13:38 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +#endif
How about defining `WOLFMQTT_TOPIC_NAME` in `user_settings.h` ?

You'll need to add a `#ifndef` check in `examples/mqttexample.h` around the default definition.

2023-05-01 13:41 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> +#endif
Instead, define `DEFAULT_MQTT_HOST` in user_settings.h. This already has an `#ifndef` check in `examples/mqttexample.h`

2023-05-01 13:50 UTC, embhorn commented on zephyr/wolfMQTT_user_settings.h
Usually the file named `user_settings.h` is picked up from the project include path when `WOLFMQTT_USER_SETTINGS` in CFLAGS. By using a different file name, you had to add this in `mqtt_types.h`

```
#ifdef CONFIG_WOLFMQTT_SETTINGS_FILE
#include CONFIG_WOLFMQTT_SETTINGS_FILE
#endif
```

2023-05-01 14:31 UTC, embhorn requested changes

2023-05-08 14:23 UTC, julek-wolfssl commented on zephyr/wolfMQTT_user_settings.h
In Zephyr both wolfSSL and wolfMQTT are compiled at the same time and linked into one executable. Is there any worry of accidentally including the wolfSSL `user_settings.h` file?

2023-05-08 14:59 UTC, julek-wolfssl commented on zephyr/wolfMQTT_user_settings.h
Thanks @dgarske. I'll change the defaults accordingly. I'll leave the wolfSSL `user_settings.h` stuff as is since it may be used by users.

2023-05-09 13:01 UTC, embhorn commented on zephyr/README.md
Could you add a short description and a forward link to this doc in the main readme?

2023-05-10 18:29 UTC, embhorn reviewed
Looking good. Please see comments.

2023-05-10 18:29 UTC, embhorn commented on examples/mqttexample.c
> +    #elif defined(WOLFMQTT_ZEPHYR)
This is for `#if !defined(NO_FILESYSTEM)`. Would it make sense to have it be `#else` instead of `#elif defined(WOLFMQTT_ZEPHYR)` ?

2023-05-10 18:29 UTC, embhorn commented on wolfmqtt/mqtt_client.h
> -    /* If options.h is missing use the "./configure" script. Otherwise, copy
Is this not a problem for VS builds anymore?

2023-05-10 18:29 UTC, embhorn commented on examples/mqttclient/mqttclient.c
> + * way to check the version of Zephyr at compile time so support the latest. */
I was really hoping to not have port specific code in here. After that commit is in a release can we revisit this?

2023-05-10 20:48 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +#endif
Using `WOLFMQTT_TOPIC_NAME`.

2023-05-10 20:48 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +#endif
Using `WOLFMQTT_DEFAULT_TLS` in user settings.

2023-05-10 20:48 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +#endif
Using `DEFAULT_MQTT_HOST`.

2023-05-10 20:49 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> +#endif
Using the default ports that depend on TLS.

2023-05-10 20:49 UTC, julek-wolfssl commented on wolfmqtt/mqtt_types.h
> +#endif
Renamed.

2023-05-10 20:49 UTC, julek-wolfssl commented on wolfmqtt/mqtt_types.h
> +#endif
Moved to `user_settings.h`.

2023-05-10 20:51 UTC, julek-wolfssl commented on examples/mqttexample.c
> +    #elif defined(WOLFMQTT_ZEPHYR)
I gated it on `WOLFMQTT_ZEPHYR` due to the `#if 0` that was in there. It achieves the same and new configurations that want this section to be active can add the configs here.

2023-05-10 20:53 UTC, julek-wolfssl commented on wolfmqtt/mqtt_client.h
> -    /* If options.h is missing use the "./configure" script. Otherwise, copy
Adding comment back in. Not sure why I deleted it.

2023-05-10 20:55 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> + * way to check the version of Zephyr at compile time so support the latest. */
I can go the `NO_MAIN_DRIVER` route if you prefer that?

2023-05-11 15:29 UTC, julek-wolfssl commented on examples/mqttclient/mqttclient.c
> + * way to check the version of Zephyr at compile time so support the latest. */
Changed to use `NO_MAIN_DRIVER`.

2023-05-12 02:06 UTC, embhorn submitted a review, later dismissed
Excellent, @julek-wolfssl ! Thanks for adding bwrap to the tests, that is a huge improvement in itself.

Dla mnie wygląda dobrze!

2023-05-15 20:41 UTC, julek-wolfssl commented
@embhorn @dgarske 
Added a github action to build and run tests against zephyr. Had to modify the user settings include in `mqtt_types.h`.

2023-05-16 17:38 UTC, embhorn approved these changes

2023-05-17 13:39 UTC, dgarske approved these changes

2023-05-17 13:40 UTC, merged