Aws example client improvement & sanitizer fixes
wolfSSL/wolfMQTT pull request #334
Opened 2023-05-23 20:18 UTC by lealem47

- Use files instead of buffers for certs/keys in `awsiot.c` and add in a callable main.
- Fixes for customer sanitizer

2023-05-23 20:27 UTC, dgarske requested changes

2023-05-23 20:27 UTC, dgarske commented on examples/aws/awsiot.c
> -        rc = wolfSSL_CTX_load_verify_buffer(client->tls.ctx,
I did this so the example could run without a file system. Why are you moving these to files? Can we keep a way to do `NO_FILESYSTEM`? What are the .rej files?

2023-05-23 20:27 UTC, dgarske commented on examples/aws/awsiot.c
> +    int awsiot_main(int argc, char** argv)
What is the point of this? Why not build with `NO_MAIN_DRIVER` and call `awsiot_test`?

2023-05-23 20:27 UTC, dgarske commented on examples/aws/awsiot.h
> +#ifdef __cplusplus
Thank you for adding the missing C++ header wrappers. Please check if there are any others.

2023-05-23 20:27 UTC, dgarske commented on examples/mqttport.h
>      #define GET_SOCK_ERROR(f,s,o,e) \
A macro as a function is a bit different (you added a return)... Why not just use the getsockopt return code directly? 
Or re-write with something like this. Or fix the calls to `GET_SOCK_ERROR` to handle the return code??

```
#define GET_SOCK_ERROR(f,s,o,e) ({ \
    int _ret; \
    socklen_t len = sizeof(so_error); \
    _ret = getsockopt((f), (s), (o), &(e), &len); \
    _ret; \
)}
```

2023-05-23 22:23 UTC, lealem47 commented on examples/aws/awsiot.c
> -        rc = wolfSSL_CTX_load_verify_buffer(client->tls.ctx,
It was suggested by the customer but I had not considered the NO_FILESYSTEM case. I'll restore it

2023-05-23 22:26 UTC, lealem47 commented on examples/aws/awsiot.c
> +    int awsiot_main(int argc, char** argv)
There's a good amount of setup in that `main()` that is required before `awsiot_test()`. Since the code is already there, this seemed like a convenient entry point for running the example

2023-05-23 22:26 UTC, lealem47 commented on examples/aws/awsiot.h
> +#ifdef __cplusplus
Will do

2023-05-23 22:27 UTC, lealem47 commented on examples/mqttport.h
>      #define GET_SOCK_ERROR(f,s,o,e) \
Will fix

2023-05-24 22:15 UTC, dgarske requested changes
These seem reasonable.

2023-05-24 22:15 UTC, dgarske commented on examples/mqttport.h
>      #define GET_SOCK_ERROR(f,s,o,e) \
I still would have preferred this return the code from `getsockopt` instead of assuming `rc` exists in the context of where the macro is used. This is very error prone code now.

2023-05-24 22:15 UTC, dgarske commented on examples/aws/awsiot.c
> +    int awsiot_main(int argc, char** argv)
This looks better. You are welcome to apply this coding path to the other examples.

2023-05-25 21:00 UTC, lealem47 commented on examples/aws/awsiot.c
> +    int awsiot_main(int argc, char** argv)
Will do

2023-05-25 21:50 UTC, dgarske submitted a review, later dismissed
Nice work putting NO_MAIN_DRIVER in the `MICROCHIP_MPLAB_HARMONY` mqtt_types.h. Was commenting on it then saw you did it!

2023-05-25 21:55 UTC, lealem47 commented
Thanks! The windows failure looks legit. Seems like it doesn't like the GET_SOCK_ERROR() syntax. Trying locally

2023-05-25 23:44 UTC, dgarske commented
@lealem47 windows has a build error with the new macro logic.

2023-05-26 17:58 UTC, dgarske approved these changes

2023-05-26 17:58 UTC, merged