Add mutex protection to MqttClient_NetDisconnect
wolfSSL/wolfMQTT pull request #342
Opened 2023-07-17 14:22 UTC by embhorn

Adds mutex protection and cancels all pending messages in `MqttClient_NetDisconnect`

Fixes zd16343

Customer confirms fix.

2023-07-17 15:11 UTC, embhorn commented
No idea why the macOS Build Test is failing

2023-07-19 16:21 UTC, lealem47 approved these changes

2023-07-19 17:03 UTC, lealem47 requested changes
macOS test failure looks like a true positive. Was able to produce locally, the multithreaded test just hangs. Doesn't happen on master.

2023-07-19 20:01 UTC, embhorn commented on src/mqtt_client.c
> +    wm_SemLock(&client->lockClient);
@dgarske - I removed the locks for send and recv because they should not be required for modifying the pending response list. Also was causing a failure in the MacOS CI test.

2023-07-19 20:16 UTC, dgarske commented on src/mqtt_client.c
> +    wm_SemLock(&client->lockClient);
How do we know the socket isn't busy in another thread, or do we let the OS handle that socket sig?

2023-07-19 20:29 UTC, dgarske approved these changes

2023-07-19 20:30 UTC, lealem47 approved these changes

2023-07-19 20:33 UTC, embhorn commented on src/mqtt_client.c
> +    wm_SemLock(&client->lockClient);
From this API, we are not doing IO directly, so it's okay if other threads are using the socket.

2023-07-19 22:57 UTC, merged