Adding publish and subscribe atomic client examples
wolfSSL/wolfMQTT pull request #347
Opened 2023-08-15 14:06 UTC by embhorn

New examples in `examples/pub-sub`

These can be used for quickly testing MQTT application or scripting.

By default, they connect to localhost. Specify a topic with `-n`
`./examples/pub-sub/mqtt-sub -n '#'`

`./examples/pub-sub/mqtt-pub -n test -m "Hello world!"`

Enable verbose example debug with `-d`

2023-08-15 20:34 UTC, lealem47 requested changes
Works great. Should there be a new test script for the pub-sub clients?

2023-08-15 20:34 UTC, lealem47 commented on examples/pub-sub/mqtt-sub.c
> +int mqttclient_main(int argc, char** argv)
Rename to avoid clashing names. `mqttSub_main()`. Also add that to mqtt-pub-sub.h header

2023-08-15 21:33 UTC, embhorn commented
> Should there be a new test script for the pub-sub clients?

I hadn't considered this. These are really just subsets of the mqttclient example. They could be used for testing against the protocol.

2023-08-15 21:41 UTC, lealem47 approved these changes, later dismissed

2023-08-16 17:16 UTC, embhorn commented
Fixed executable names in .gitignore

2023-08-22 17:25 UTC, dgarske approved these changes
All looks good and tests out. I notice these aren't being used yet. Are you planning to add some additional scripts to test using these?

2023-08-22 18:54 UTC, embhorn commented
> All looks good and tests out. I notice these aren't being used yet. Are you planning to add some additional scripts to test using these?

Yes, that is the intention, to better enable functional testing using these clients.

2023-10-12 00:00 UTC, merged