Add DTLS support to MQTT-SN client
wolfSSL/wolfMQTT pull request #348
Opened 2023-08-25 21:38 UTC by embhorn

Tested with mosquitto as broker, https://github.com/eclipse/paho.mqtt-sn.embedded-c as gateway.

1. To use with local mosquitto broker, edit `MQTTSNGateway/gateway.conf`
```
-BrokerName=mqtt.eclipseprojects.io
+BrokerName=localhost
```
* I had to fix a bug in the gateway (could be related to the openssl or compiler version):
```
diff --git a/MQTTSNGateway/src/linux/dtls/SensorNetwork.cpp b/MQTTSNGateway/src/linux/dtls/SensorNetwork.cpp
index 3f2dcf3..363d0ba 100644
--- a/MQTTSNGateway/src/linux/dtls/SensorNetwork.cpp
+++ b/MQTTSNGateway/src/linux/dtls/SensorNetwork.cpp
@@ -308,7 +308,7 @@ Connections::~Connections()
     {
         for (int i = 0; i < _numfds; i++)
         {
-            if (_ssls[i] > 0)
+            if (_ssls[i] > (SSL *)0)
             {
                 SSL_shutdown(_ssls[i]);
                 SSL_free(_ssls[i]);
@@ -416,7 +416,7 @@ void Connections::close(int index)
         }
     }
 
-    if (ssl > 0)
+    if (ssl > (SSL *)0)
     {
         _numfds--;
         SSL_shutdown(ssl);
```

* Build gateway with DTLS:
`<gateway-folder>/MQTTSNGateway$ ./build.sh dtls`

2. Build wolfSSL with DTLS:  `./configure --enable-dtls && make && sudo make install`
3. Build wolfMQTT with SN support:  `./configure --enable-sn && make`
4. Run the broker: `mosquitto`
5. Run the gateway: `<gateway-folder>/MQTTSNGateway$ ./bin/MQTT-SNGateway`
6. To run the wolfMQTT sn-client example with DTLS:
`./examples/sn-client/sn-client -t`

2023-08-29 20:16 UTC, lealem47 submitted a review, later dismissed
Tested and working. Perhaps add some of the PR notes into the SN example section of the README

2023-08-30 13:34 UTC, embhorn commented
> Tested and working. Perhaps add some of the PR notes into the SN example section of the README

I added a new README for the MQTT-SN examples. It was getting pretty long, so makes sense to move it.

2023-08-31 20:44 UTC, dgarske requested changes

2023-08-31 20:44 UTC, dgarske commented on examples/mqttexample.c
> +    client->tls.ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
Did you consider moving this DTLS code (WOLFSSL_DTLS) into mqtt_socket.c and have a run-time gate for the method selection, since otherwise its just the same?

2023-08-31 20:44 UTC, dgarske commented on examples/mqttnet.c
> +    #endif
This just means you got some data and instead of waiting for "all" data you just break out for DTLS. Seems fine to me. However you can likely do this for the TLS case too...

2023-08-31 20:44 UTC, dgarske commented on src/mqtt_packet.c
> +            if (client->flags & MQTT_CLIENT_FLAG_IS_TLS) {
Should we have a flag for DTLS? Seems like you could use this flag for the mqtt_socket.c TLS method?

2023-08-31 20:57 UTC, embhorn commented on examples/mqttexample.c
> +    client->tls.ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
Yeah, but `MqttSocket_Connect` is the default (i.e. when you don't set up CTX and SSL with a callback), so given that DTLS is only used with MQTT-SN (not as common as MQTT / TLS), it made sense to use the callback.

2023-08-31 21:05 UTC, dgarske commented on examples/mqttexample.c
> +    client->tls.ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
Seems like we should add a way to propagate the `MQTT_CLIENT_FLAG_IS_TLS` to mqtt_socket and add one for DTLS?

2023-09-01 14:21 UTC, embhorn commented on examples/mqttexample.c
> +    client->tls.ctx = wolfSSL_CTX_new(wolfDTLSv1_2_client_method());
I added a new API, `MqttSocket_SetDTLS`, that can be used to set the new `MQTT_CLIENT_FLAG_IS_DTLS` flag.

2023-09-01 17:01 UTC, dgarske requested changes

2023-09-01 17:33 UTC, dgarske approved these changes, later dismissed

2023-09-01 17:58 UTC, dgarske requested changes

2023-09-01 17:58 UTC, dgarske commented on src/mqtt_client.c
> +        return client->flags;
Please get the final flags before unlock.

2023-09-01 18:17 UTC, dgarske approved these changes

2023-09-01 19:23 UTC, embhorn commented
Ready for merge!

2023-09-01 19:25 UTC, merged