Refactor MQTT-SN code
wolfSSL/wolfMQTT pull request #366
Opened 2023-10-27 22:15 UTC by embhorn

2023-10-27 22:36 UTC, dgarske requested changes
Wonderful!! Thank you

2023-10-27 22:36 UTC, dgarske commented on examples/sn-client/sn-client_qos-1.c
> +#include "wolfmqtt/mqtt_sn_client.h"
For backwards compatibility you could have `mqtt_client.h` conditionally include `wolfmqtt/mqtt_sn_client.h` automatically based on `WOLFMQTT_SN`.

2023-10-31 20:45 UTC, dgarske requested changes

2023-10-31 20:45 UTC, dgarske commented on src/mqtt_sn_client.c
> +/* sn_mqtt_client.c
`sn_mqtt_client.c` -> `mqtt_sn_client.c`

2023-10-31 20:45 UTC, dgarske commented on src/mqtt_sn_packet.c
> +/* sn_mqtt_packet.c
`sn_mqtt_packet.c` -> `mqtt_sn_packet.c`.

2023-10-31 20:45 UTC, dgarske commented on src/mqtt_sn_client.c
> +static int SN_Client_WaitType(MqttClient *client, void* packet_obj,
As a future TODO... when comparing this with `MqttClient_WaitType` there are some fixes that need brought over.

2023-10-31 20:52 UTC, dgarske approved these changes

2023-10-31 20:53 UTC, embhorn commented on src/mqtt_sn_client.c
> +static int SN_Client_WaitType(MqttClient *client, void* packet_obj,
Created #367

2023-10-31 21:31 UTC, merged