Fixes for non-blocking with larger payload and improvements to the test and examples
wolfSSL/wolfMQTT pull request #373
Opened 2023-11-22 21:04 UTC by dgarske

* Fix for continue during variable part of the header. A continue in the middle of variable would not correctly process for large messages.
* Further improve WOLFMQTT_TEST_NONBLOCK.
* Fixes for using the `-f [file]` option with examples. 
* Allow build-time override of `MAX_BUFFER_SIZE` in examples.

2023-11-22 23:28 UTC, dgarske commented
FYI: I can reproduce the error locally. Getting a disconnected due to protocol error from broker, which for some reason leaves the local broker instance running still:

```
Broker PID is 29060
1700688555: mosquitto version 2.0.11 starting
1700688555: Config loaded from scripts/broker_test/mosquitto.conf.
1700688555: Opening ipv4 listen socket on port 11883.
1700688555: Opening ipv6 listen socket on port 11883.
1700688555: Opening ipv4 listen socket on port 18883.
1700688555: Opening ipv6 listen socket on port 18883.
1700688555: mosquitto version 2.0.11 running
Base args: -T -C 2000 -h localhost -p 11883
1700688555: New connection from 127.0.0.1:39066 on port 11883.
1700688555: Client <unknown> disconnected due to protocol error.
MQTT Client: QoS 0, Use TLS 0
MQTT Net Init: Success (0)
MQTT Init: Success (0)
NetConnect: Host localhost, Port 11883, Timeout 5000 ms, Use TLS 0
MQTT Socket Connect: Success (0)
MQTT Connect: Proto (v3.1.1), Continue (-101)
MQTT Disconnect: Success (0)
MQTT Socket Disconnect: Success (0)
1700688555: New connection from 127.0.0.1:39072 on port 11883.
1700688555: Client <unknown> disconnected due to protocol error.
```

Will investigate on Friday.

2023-11-24 17:35 UTC, dgarske commented
Tests with TLS and non-block are failing due to this bug -> https://github.com/wolfSSL/wolfssl/pull/7001

2023-11-27 22:22 UTC, embhorn requested changes
Update - needed to update wolfSSL first!

-----Ignore----
Seeing failures with 
`./configure --enable-mt --enable-nonblock CFLAGS="-DWOLFMQTT_TEST_NONBLOCK"`

```
ASS: scripts/client.test
FAIL: scripts/multithread.test
PASS: scripts/firmware.test
PASS: scripts/awsiot.test
FAIL: scripts/nbclient.test
PASS: scripts/azureiothub.test
```

2023-11-28 17:23 UTC, dgarske commented
Customer is fully happy. No outstanding issues. This PR is ready for merge.

2023-11-28 17:34 UTC, embhorn approved these changes

2023-11-28 17:34 UTC, merged