Add curl easy socket backend.
wolfSSL/wolfMQTT pull request #380
Opened 2023-12-06 18:04 UTC by philljj

# Description

Added libcurl easy socket backend support for testing purposes.

Built with:
```
./configure --enable-curl --disable-tls
```

The `--disable-tls` is required because TLS is handled by libcurl.

# Prereqs
- wolfssl has been built with `--enable-curl` and installed to `/usr/local`.
- libcurl has been built with `--with-wolfssl` and installed to `/usr/local`.

# Testing

Added new example `examples/mqttcurl.c`. The example will automatically use TLS depending on the port. If using TLS a CAfile can be passed in with -A:

```
$./examples/mqttclient/mqttclient -p 8883 -A mosquitto.org.crt 
MQTT Client: QoS 0, Use TLS 0
MQTT Net Init: Success (0)
MQTT Init: Success (0)
*   Trying [2001:41d0:1:925e::1]:8883...
* Connected to test.mosquitto.org (2001:41d0:1:925e::1) port 8883
* successfully set certificate verify locations:
*  CAfile: mosquitto.org.crt
*  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* using HTTP/1.x
* Connection #0 to host test.mosquitto.org left intact
MQTT Socket Connect: Success (0)
MQTT Connect: Proto (v3.1.1), Success (0)
MQTT Connect Ack: Return Code 0, Session Present 0
MQTT Subscribe: Success (0)
  Topic wolfMQTT/example/testTopic, Qos 0, Return Code 0
MQTT Publish: Topic wolfMQTT/example/testTopic, ID 2, Success (0)
MQTT Waiting for message...
MQTT Message: Topic wolfMQTT/example/testTopic, Qos 0, Len 4
Payload (0 - 4) printing 4 bytes:
test
MQTT Message: Done
```

```
$./examples/mqttclient/mqttclient -p 1883
MQTT Client: QoS 0, Use TLS 0
MQTT Net Init: Success (0)
MQTT Init: Success (0)
*   Trying [2001:41d0:1:925e::1]:1883...
* Connected to test.mosquitto.org (2001:41d0:1:925e::1) port 1883
* Connection #0 to host test.mosquitto.org left intact
MQTT Socket Connect: Success (0)
MQTT Connect: Proto (v3.1.1), Success (0)
MQTT Connect Ack: Return Code 0, Session Present 0
MQTT Subscribe: Success (0)
  Topic wolfMQTT/example/testTopic, Qos 0, Return Code 0
MQTT Publish: Topic wolfMQTT/example/testTopic, ID 2, Success (0)
MQTT Waiting for message...
MQTT Message: Topic wolfMQTT/example/testTopic, Qos 0, Len 4
Payload (0 - 4) printing 4 bytes:
test
MQTT Message: Done
```

2023-12-06 18:20 UTC, dgarske requested changes

2023-12-06 18:20 UTC, dgarske commented on configure.ac
> +        AC_MSG_ERROR([--enable-tls and --enable-curl are incompatible])
Do these really need to be incompatible? Just seems odd to forcefully have to disable TLS here to get the CURL easy sockets to work.

2023-12-06 18:20 UTC, dgarske commented on src/mqtt_curl.c
> +int MqttSocket_Init(MqttClient *client, MqttNet *net)
My preference is to to all this into mqtt_socket.c directly. Defer to @embhorn for his input.

2023-12-06 18:20 UTC, dgarske commented on src/mqtt_curl.c
> +#include "wolfmqtt/mqtt_client.h"
We must support building sources directly. This while file needs wrapped with `ENABLE_MQTT_CURL`

2023-12-06 18:20 UTC, dgarske commented on examples/mqttcurl.c
> +#if defined(WOLFMQTT_DEBUG_CURL_VERBOSE)
Please use existing `WOLFMQTT_DEBUG_SOCKET` or add to the `--enable-debug=verbose` list.

2023-12-06 18:20 UTC, dgarske commented on examples/mqttcurl.c
> +        return MQTT_CODE_ERROR_MEMORY;
Please refactor to single return point. Can't you leak handles returning early?

2023-12-06 18:32 UTC, philljj commented on src/mqtt_curl.c
> +int MqttSocket_Init(MqttClient *client, MqttNet *net)
There is a lot of code gated behind `ENABLE_MQTT_TLS` and in `mqtt_socket.c` that does lower level API calls on WOLFSSL and SSL_CTX structs (and sockets) that would conflict with the goal of letting libcurl handle it behind the scenes.

It just seemed simpler to isolate the libcurl testing code in its own place, but I'm open to changing it.

2023-12-06 18:32 UTC, philljj commented on src/mqtt_curl.c
> +#include "wolfmqtt/mqtt_client.h"
Good catch!

2023-12-06 21:02 UTC, embhorn requested changes

2023-12-06 21:02 UTC, embhorn commented on src/mqtt_curl.c
> +int MqttSocket_Init(MqttClient *client, MqttNet *net)
I was envisioning this curl part going in to the net abstraction ( examples/mqttnet.c )

2023-12-07 05:08 UTC, philljj commented on src/mqtt_curl.c
> +int MqttSocket_Init(MqttClient *client, MqttNet *net)
I consolidated `examples/mqttcurl.c` into `mqttnet.c`.

Working on `mqtt_curl.c` and `mqtt_socket.c` now.

2023-12-07 05:13 UTC, philljj commented on examples/mqttcurl.c
> +#if defined(WOLFMQTT_DEBUG_CURL_VERBOSE)
I changed them to `WOLFMQTT_DEBUG_SOCKET`.

2023-12-07 05:16 UTC, philljj commented on examples/mqttcurl.c
> +        return MQTT_CODE_ERROR_MEMORY;
Done! Refactored the setopt and curl_easy_perform to a separate function, and the handle is cleaned up if that function fails.

2023-12-07 06:01 UTC, philljj commented on src/mqtt_curl.c
> +int MqttSocket_Init(MqttClient *client, MqttNet *net)
`mqtt_curl.c` is combined into `mqtt_socket.c` now.

I'll figure out a way for `--enable-curl` to not conflict with `--enable-tls` next.

2023-12-08 15:10 UTC, embhorn commented on configure.ac
Please add the libcurl support option to the configuration summary

2023-12-08 15:12 UTC, embhorn reviewed
Could you add a section to the readme about using the libcurl option?

2023-12-08 16:21 UTC, philljj commented
The client and firmware tests work with `--enable-curl` now, and the curl support includes TLS and mTLS.

Will add a github action now.

2023-12-08 16:37 UTC, dgarske requested changes
Great work. Looking forward to the GitHub CI action being in place.

2023-12-08 16:37 UTC, dgarske commented on examples/mqttnet.c
> +    if(for_recv) {
NIT: Please use `if (` ... add space.

2023-12-08 16:37 UTC, dgarske commented on examples/mqttnet.c
> +    /* Toggle with option, or put behind debug define? */
Please wrap with `DEBUG_WOLFMQTT`

2023-12-08 17:33 UTC, philljj commented
Added the curl ubuntu CI test in a separate workflow
```.github/workflows/ubuntu-check-curl.yml```
just to avoid potential side-effects between the with and without curl builds.

2023-12-08 19:02 UTC, philljj commented on src/mqtt_socket.c
> +        curl_global_cleanup();
I think mqttnet.c is too low level.

Would want it somewhere higher level where it's among the first/last functions called on init/exit.

2023-12-08 19:04 UTC, philljj commented on src/mqtt_socket.c
> +        curl_global_cleanup();
mqtt_socket just seemed natural because that's where we call wolfSSL_Init/cleanup.

2023-12-08 19:12 UTC, dgarske requested changes

2023-12-08 19:12 UTC, dgarske commented on examples/mqttnet.c
> +    CURLcode res = 0;
```
examples/mqttnet.c:435:14: error: cannot initialize a variable of type 'CURLcode' with an rvalue of type 'int'
    CURLcode res = 0;
             ^     ~
examples/mqttnet.c:647:21: error: cannot initialize a variable of type 'CURLcode' with an rvalue of type 'int'
    CURLcode        res = 0;
                    ^     ~
examples/mqttnet.c:714:21: error: cannot initialize a variable of type 'CURLcode' with an rvalue of type 'int'
    CURLcode        res = 0;
                    ^     ~
```

2023-12-08 21:15 UTC, embhorn requested changes
`./configure --enable-all --enable-curl` produces build errors:
```
examples/mqttnet.c: In function ‘SN_ClientNet_Init’:
examples/mqttnet.c:1442:24: error: ‘SN_NetConnect’ undeclared (first use in this function); did you mean ‘NetConnect’?
 1442 |         net->connect = SN_NetConnect;
      |                        ^~~~~~~~~~~~~
      |                        NetConnect
examples/mqttnet.c:1442:24: note: each undeclared identifier is reported only once for each function it appears in
examples/mqttnet.c:1445:21: error: ‘NetPeek’ undeclared (first use in this function)
 1445 |         net->peek = NetPeek;
      |                     ^~~~~~~
```

2023-12-08 21:24 UTC, philljj commented
I think several of these combinations need to be rejected in configure.ac. Looking at this.

2023-12-08 21:26 UTC, embhorn requested changes
In `examples/mqttclient/mqttclient`, the client gets into the "Read loop" and fails to send messages typed. Also the client never sends a ping, just exits on timeout:
```
MQTT Waiting for message...
MQTT Message: Topic wolfMQTT/example/testTopic, Qos 0, Len 4
Payload (0 - 4) printing 4 bytes:
test
MQTT Message: Done
test
error: recvd 0 bytes, expected 2
Network Error Callback: Error (libcurl) (error -16)
MQTT Message Wait: Error (libcurl) (-16)
MQTT Disconnect: Success (0)
MQTT Socket Disconnect: Success (0)
```

2023-12-08 22:44 UTC, philljj commented
Also, I'll document more clearly which `--enable-` options are compatible with `--enable-curl`.

2023-12-11 16:59 UTC, dgarske approved these changes
@embhorn when you are happy merge please.

2023-12-11 22:43 UTC, embhorn approved these changes
Fantastic!

2023-12-11 22:43 UTC, merged