Fix string prop OOB read
wolfSSL/wolfMQTT pull request #394
Opened 2024-02-02 17:51 UTC by embhorn

Check status and full size of `MqttDecode_String` against buf length.

Fixes zd17257

> OSS-Fuzz #46212: wolfMQTT: Out-of-bounds read on i386

2024-02-02 21:54 UTC, philljj approved these changes, later dismissed
Looks good to me. Just waiting on Guido's feedback.

2024-02-23 14:35 UTC, embhorn commented
Fix has been confirmed by Guido

2024-02-23 15:38 UTC, philljj requested changes
All good except a few missing (word32) casts here I think:
```
src/mqtt_packet.c:503:21: error: comparison of integers of different signs: 'word32' (aka 'unsigned int') and 'int' [-Werror,-Wsign-compare]
        if (buf_len < (buf - pbuf)) {
            ~~~~~~~ ^  ~~~~~~~~~~
src/mqtt_packet.c:569:29: error: comparison of integers of different signs: 'word32' (aka 'unsigned int') and 'int' [-Werror,-Wsign-compare]
                if (buf_len < (buf - pbuf)) {
                    ~~~~~~~ ^  ~~~~~~~~~~
2 errors generated.
```

2024-02-23 16:02 UTC, philljj approved these changes

2024-02-23 16:02 UTC, merged